### ISSUE TITLE
Provide Pretrained model

### ISSUE THREAD

**Issue by mehullala** [AdroitAnandAI/Indian-Accent-Speech-Recognition#1]
Hello,
Loved your article and your work. Can you provide trained model along with access to raw data for references. 
Really appreciate it.

**Comment by AdroitAnandAI** [comment]
Thanks @mehullala As requested, I have uploaded the pre-trained model and trie file in a folder. You can use the original lm.binary (link is given in the .txt file)

The raw files given by IIT Madras is protected under license not to make it public. 

Hope it helps.

**Comment by mehullala** [comment]
I am assuming you are using deepspeech 0.4.1 but I am getting following error, please see if you can help out:

Not found: Op type not registered 'AudioSpectrogram' in binary running on ip-172-31-6-242. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
Traceback (most recent call last):
  File "/home/tech/mehul/deepspeech/venv/bin/deepspeech", line 8, in <module>
    sys.exit(main())
  File "/home/tech/mehul/deepspeech/venv/lib/python3.5/site-packages/deepspeech/client.py", line 80, in main
    ds = Model(args.model, N_FEATURES, N_CONTEXT, args.alphabet, BEAM_WIDTH)
  File "/home/tech/mehul/deepspeech/venv/lib/python3.5/site-packages/deepspeech/__init__.py", line 14, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 5

**Comment by AdroitAnandAI** [comment]
Try deepspeech.Model('.pbmm file',Band_width)

ds = Model(model, N_FEATURES, N_CONTEXT, alphabet, BEAM_WIDTH) will work if
you install deepspeech version 0.4.1 0r 0.5.1 in your python environment

You can try this:
file_path = '/content/drive/My Drive/Deepspeech models/output_graph
(1).pbmm'
Band_width = 500
model = deepspeech.Model(file_path, Band_width)
alpha = 0.75
Beta = 1.85
lm_file = '/content/drive/My Drive/Deepspeech models/lm.binary'
trie = '/content/drive/My Drive/Deepspeech models/trie'
model.enableDecoderWithLM(lm_file,trie,alpha,Beta)

**Comment by AdroitAnandAI** [comment]
Try deepspeech.Model('.pbmm file',Band_width)

ds = Model(model, N_FEATURES, N_CONTEXT, alphabet, BEAM_WIDTH) will work if
you install deepspeech version 0.4.1 0r 0.5.1 in your python environment

You can try this:
file_path = '/content/drive/My Drive/Deepspeech models/output_graph
(1).pbmm'
Band_width = 500
model = deepspeech.Model(file_path, Band_width)
alpha = 0.75
Beta = 1.85
lm_file = '/content/drive/My Drive/Deepspeech models/lm.binary'
trie = '/content/drive/My Drive/Deepspeech models/trie'
model.enableDecoderWithLM(lm_file,trie,alpha,Beta)

**Comment by mehullala** [comment]
@AdroitAnandAI Thanks for the help but it seems error is because of tensorflow version mismatch.
Can you please tell me which version you used during training of model?

Thanks!

**Comment by AdroitAnandAI** [comment]
tensorflow-gpu==2.0.0-beta0
