### ISSUE TITLE
Missing licence File

### ISSUE THREAD

**Issue by ri5h** [AdroitAnandAI/Indian-Accent-Speech-Recognition#3]
I am assuming that the code and model provided in the public repository is available for reuse in other applications and personal projects but It would be great to have a licence such as MIT added to the repository to help in making the decision easier.

**Comment by AdroitAnandAI** [comment]
Fixed the problem

**Comment by Vrushali-anil-Chaudhari** [comment]
Can you provide the pre-trained model as it is not accessible now?
